name: Collaborative Workflow

on: 
  push: 
    branches: 
      - master

jobs: 
  update_html_and_readme: 
    runs-on: ubuntu-latest  
    steps: 
      # Step 1: Checkout the repository 
      - name: Checkout Repository  
        uses: actions/checkout@v3

      # Step 2: Update index.html based on GitHub actor
      - name: Update HTML if actor is Team Leader
        if: github.actor == 'team-leader-username'
        run: |
          sed -i '/<\/body>/i <p>Updated by Team Leader on "'$(date)'"</p>' index.html

      - name: Update HTML if actor is Member 1
        if: github.actor == 'member1-username'
        run: |
          sed -i '/<\/body>/i <p>Updated by Member 1 on "'$(date)'"</p>' index.html

      - name: Update HTML if actor is Member 2
        if: github.actor == 'member2-username'
        run: |
          sed -i '/<\/body>/i <p>Updated by Member 2 on "'$(date)'"</p>' index.html

      # ✅ Step 3: Update README
      - name: Append update log to README.md
        run: |
          echo "### Updated by ${{ github.actor }} on $(date '+%Y-%m-%d %H:%M:%S') [Commit: $(git rev-parse --short HEAD)]" >> README.md

      # ✅ Step 4: Commit and Push Changes
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Workflow: Updated HTML and README for ${{ github.actor }}" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
